### ISSUE TITLE
Make `Cmdliner.Arg.conv` abstract and remove deprecated interfaces for 2.0

### ISSUE THREAD

**Issue by dbuenzli** [dbuenzli/cmdliner#206]
This issue keeps track of breaking changes for 2.0 these are: 

1. The commit that makes `Cmdliner.Arg.conv` abstract. Announced it would become in 2017, sadly it was not possible to visibly deprecate it.
1. Commits that remove interfaces that have been deprecated before 2.0. 

# Instructions 

Projects can handle all breaking changes performed by 2.0 and still compile with `cmdliner.1.3.0`.

If you have been notified that your project will not compile with 2.0 and want to make sure it does please follow these instructions:

1. Compile your project with `opam pin add cmdliner.1.3.0` and fix the deprecation warnings as suggested. These may not show up if you silenced them in which case either unsilence them or go to 2. they will show up as "Unbound value" errors.
2. Compile your projects with `opam pin add cmdliner --dev` and fix remaining compilation errors. These should mainly be due to the `Arg.conv` becoming an abstract type and can be tackled:
   * Tweaking your polymorphic variant result type into regular `result` variants and use either [`Arg.conv'`](https://erratique.ch/software/cmdliner/doc/Cmdliner/Arg/index.html#val-conv') or [`Arg.conv`](https://erratique.ch/software/cmdliner/doc/Cmdliner/Arg/index.html#val-conv) on your pairs.
   * Use the accessors [`Arg.conv_parser`](https://erratique.ch/software/cmdliner/doc/Cmdliner/Arg/index.html#val-conv_parser) and [`Arg.conv_printer`](https://erratique.ch/software/cmdliner/doc/Cmdliner/Arg/index.html#val-conv_printer) if you were deconstructing `Arg.conv` values as pairs.

3. Update your opam file with `cmdliner {>= "1.3.0"}`
   

# Tracking a few project updates 

Tracking a few project updates: 

* https://github.com/ocaml/odoc/pull/1328
* https://github.com/OCamlPro/ocp-indent/pull/328
* https://github.com/OCamlPro/ocp-index/pull/175

See also the references below.
